name: saptet ci/cd
on:
  push:
    branches: [ci_cd_demo]

jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up our JDK environment
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '11'
            cache: 'gradle'

        - run: |
                ln -s ${ANDROID_HOME}/build-tools/31.0.0/d8 ${ANDROID_HOME}/build-tools/31.0.0/dx |
                ln -s ${ANDROID_HOME}/build-tools/31.0.0/lib/d8.jar ${ANDROID_HOME}/build-tools/31.0.0/lib/dx.jar

        - name: Setup gradle
          uses: gradle/gradle-build-action@v2

        - name: Execute Gradle build
          run: ./gradlew assembleDebug

        - name: list Apks Debug
          run: ls -lrt app/build/outputs/apk/debug

        - name: Deploy to Firebase
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            groups: testers
            file: app/build/outputs/apk/debug/app-debug.apk