name: saptet ci/cd
on:
  push:
    branches: [ci_cd_demo]

jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up our JDK environment
          uses: actions/setup-java@v2
          with:
            distribution: temurin
            java-version: 11
        - name: Setup gradle
          uses: gradle/gradle-build-action@v2

        - name: Execute Gradle build
          run: ./gradlew assembleDebug